version: 2.1

jobs:
    build:
        working_directory: ~/wideq
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                command: sudo pip install tox
            - restore_cache:
                key: tox-{{ checksum "tox.ini" }}
                paths: [".tox"]
            - run:
                command: tox -e py37,flake8
            - save_cache:
                key: tox-{{ checksum "tox.ini" }}
                paths: [".tox"]
